### ISSUE TITLE
Don't hardcode user id and password

### ISSUE THREAD

**Issue by gau1991** [nagarajabalur/mywordpress#2]
Your wp-config.php template contains following hardcoded values.

```
// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('DB_NAME', 'wordpressdb');
/** MySQL database username */
define('DB_USER', 'wordpressuser');
/** MySQL database password */
define('DB_PASSWORD', 'password123');
/** MySQL hostname */
define('DB_HOST', 'localhost');
```

Please create Chef attribute for same

**Comment by nagarajabalur** [comment]
created chef attributes:

#attributes for DB
default['mywordpress']['db']['name'] = "wordpressdb"
default['mywordpress']['db']['user'] = "wordpressuser"
default['mywordpress']['db']['root_password'] = "password123"
default['mywordpress']['db']['password'] = "password123"
