### ISSUE TITLE
Always download into Chef Cache

### ISSUE THREAD

**Issue by gau1991** [nagarajabalur/mywordpress#4]
Instead of using `/tmp` use Chef cache for downloading using remote_file resource.

```
# download the latest wordpress tar file
remote_file '/etc/latest.tar.gz' do
  source 'http://wordpress.org/latest.tar.gz'
  owner 'root'
  group 'root'
  mode '0755'
end
```

**Comment by nagarajabalur** [comment]
using chef cache to download the remote files:

filepath = Chef::Config[:file_cache_path] + '/latest.tar.gz'

remote_file filepath do
  source sourceurl
  owner 'root'
  group 'root'
  mode '0755'
end
