### ISSUE TITLE
Resources are not idempotent

### ISSUE THREAD

**Issue by gau1991** [nagarajabalur/mywordpress#5]
Following resources are not idempotent.

```

# extract the downloaded tar file
execute 'extract_some_tar' do
  command 'tar xzvf latest.tar.gz'
  cwd '/etc'
  only_if { File.exist?('/etc/latest.tar.gz') }
end

# copy the content of wordpress to /var/www/html
execute 'copy the wordpress content' do
  command 'cp -r /etc/wordpress/* /var/www/html'
end
```

Always make sure that your resources are idempotent.

**Comment by nagarajabalur** [comment]
added idempotent resources by adding :+1: 

# extract the downloaded tar file

execute 'extract_some_tar' do
  command 'tar xzvf latest.tar.gz'
  cwd '/tmp/kitchen/cache'
  not_if { File.exists?("/tmp/kitchen/cache/wordpress/index.php") }
end

# copy the content of wordpress to /var/www/html

execute 'copy the wordpress content' do
  command 'cp -r /tmp/kitchen/cache/wordpress/\* /var/www/html'
  not_if { File.exists?("/var/www/html/wordpress/index.php") }
end
