### ISSUE TITLE
Create attribute for WordPress version

### ISSUE THREAD

**Issue by gau1991** [nagarajabalur/mywordpress#6]
You can create attribute for WordPress version. Its Default will be latest.

```
remote_file '/etc/latest.tar.gz' do
  source 'http://wordpress.org/latest.tar.gz'
  owner 'root'
  group 'root'
  mode '0755'
end
```

**Comment by nagarajabalur** [comment]
added atributes for download perticular version of tar ball
#attributes for wordpress 
default['wordpress']['version'] = 'latest'
default['wordpress']['url'] = "https://wordpress.org/wordpress-#{node['wordpress']['version']}.tar.gz"
