### ISSUE TITLE
Wrong owner and group

### ISSUE THREAD

**Issue by gau1991** [nagarajabalur/mywordpress#7]
Webroot files must not have root as owner and group.

```
# added the mysql db config's to  wp-config.php file
cookbook_file '/var/www/html/wp-config.php' do
  source 'wp-config.php'
  owner 'root'
  group 'root'
  mode '0644'
end
```

**Comment by nagarajabalur** [comment]
added apache as user and group:

# added the mysql db config's to  wp-config.php template

template '/var/www/html/wp-config.php' do
  source 'wp-config.php.erb'
  owner 'apache'
  group 'apache'
  mode '0644'
end
